name: wuchuheng_email_storage
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
 #   path: ^1.8.0
 enough_mail: ^2.1.1
 wuchuheng_isolate_channel: ^0.0.24
 json_annotation: ^4.7.0
 json_serializable: ^6.5.4
 wuchuheng_env: ^1.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.3.2
