name: Library testing

on:
  push:
    branches:
      - dev
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
      - run: flutter --version
      - run: dart --version
      - name: Install dependencies
        run: dart pub get
      - name: Set up env
        run: echo 'IMAP_HOST=${{ secrets.IMAP_HOST}}' >> test/.env
      - run: echo 'SMTP_HOST=${{ secrets.SMTP_HOST}}' >> test/.env
      - run: echo 'USERNAME=${{ secrets.USERNAME}}' >> test/.env
      - run: echo 'PASSWORD=${{ secrets.PASSWORD}}' >> test/.env
      - run: echo 'STORAGE_NAME=${{ secrets.STORAGE_NAME}}' >> test/.env
      - run: echo "LOCAL_STORAGE_PATH=$(pwd)/.cache" >> test/.env
      - run: cat test/.env
      - name: Testing
        run: dart test